# select silverblue-main as the base image
FROM ghcr.io/ublue-os/silverblue-main

# install wine on top
RUN rpm-ostree install wine 

COPY --from=ghcr.io/ublue-os/bling:latest /modules /tmp/modules/
RUN /tmp/modules/default-flatpaks/default-flatpaks.sh '{"system": {"install": ["org.kde.kdenlive", "com.obsproject.Studio"]}}'

# finalize the build
RUN rm -rf /tmp/* /var/* && ostree container commit 
